name: Testing

on: [push]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Alpine
        uses: mileschou/docker-lapis/alpine@master
  debian:
    runs-on: ubuntu-latest
    steps:
      - name: Debian
        uses: mileschou/docker-lapis@master
